version: '3.3'
services:
  payment-nginx:
    build: payment-process-frontend/.
    container_name: payment-nginx
    ports:
      - "80:80"
    networks: 
      - container-network
    depends_on:
      - "payment-api"
      
  payment-api:
    build: payment-process-api/.
    container_name: payment-api
    ports:
      - "8080:8080"
    networks: 
      - container-network
    depends_on:
      - "payment-rabbitmq"
      - "payment-db"

  payment-rabbitmq:
    image: rabbitmq:management
    container_name: payment-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks: 
      - container-network
  
  payment-db:
    image: postgres:9.4.5
    container_name: payment-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: DB_PAYMENT_PROCESS
    ports:
      - "5432:5432"
    networks: 
      - container-network

networks: 
    container-network:
        driver: bridge